# Generated by Django 4.0.2 on 2022-02-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermovie_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
