# Generated by Django 4.0.2 on 2022-02-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_film_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='views_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
