# Generated by Django 4.0.2 on 2022-02-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_film_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='views_count',
        ),
    ]
