# Generated by Django 4.0.2 on 2022-02-22 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_film_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_movie', to='users.film'),
        ),
        migrations.AlterField(
            model_name='usermovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_movie', to=settings.AUTH_USER_MODEL),
        ),
    ]
